kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: horus
rules:
- apiGroups: ["", "extensions", "networking.k8s.io", "discovery.k8s.io"]
  resources: ["ingresses", "namespaces", "endpointslices"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: horus
  namespace: websites
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: horus
subjects:
- kind: ServiceAccount
  name: horus
  namespace: websites
roleRef:
  kind: ClusterRole
  name: horus
  apiGroup: rbac.authorization.k8s.io